### ISSUE TITLE
Android redirect URL

### ISSUE THREAD

**Issue by markfili** [mollie/demo-checkout-android#3]
Hi there,

I'm trying to implement the [Basic Flow](https://github.com/mollie/demo-checkout-android/blob/main/images/FlowBasic.gif) but I'm having trouble getting the app to open again after Payment process has completed.

After selecting "Paid" and clicking on "Continue", the browser opens this page: https://www.mollie.com/checkout/3dfoot://mollie-payment-return.

3dfoot is the scheme and mollie-payment-return the host for filtering intents added to AndroidManifest. I've tested broadcasting an intent with these settings and it opened the app without problems.

Do you have any suggestions?

Thank you

**Comment by fjbender** [comment]
I don't think that `3dfoot` is a valid scheme, see [RFC3986 Section 3.1](https://datatracker.ietf.org/doc/html/rfc3986#section-3.1). Can you try with `threedf` or so instead?

**Comment by markfili** [comment]
thank you for your answer, it occurred to me that the number could be responsible right after I clicked to create the issue, we're trying now...

**Comment by markfili** [comment]
you were right, @fjbender, the scheme was incorrect. I've missed that option. thank you.
